"""SQLite schema + helpers for the Smart Agriculture system.

Placeholder counts are generated by ``_sql()`` from the column list so the
number of ``?`` always matches the number of columns.

Tables
------
devices       : registered field nodes (ESP32, gateways, ...)
readings      : every sensor frame from every device
alerts        : rule-engine outputs (drought, waterlogging, pests risk, ...)
recommendations : human-readable actions produced from alerts
actuators     : desired/actual state of pumps, valves, fans
irrigation_events : every pump/valve action with reason and duration
weather       : cached weather/forecast calls
"""
import csv
import datetime
import os
import sqlite3

from config import DB_PATH, EXPORT_DIR

SCHEMA = """
CREATE TABLE IF NOT EXISTS devices(
    id INTEGER PRIMARY KEY, device_id TEXT UNIQUE, plot TEXT, crop TEXT,
    lat REAL, lon REAL, last_seen TEXT, created_at TEXT DEFAULT (datetime('now','localtime')));

CREATE TABLE IF NOT EXISTS readings(
    id INTEGER PRIMARY KEY, ts TEXT DEFAULT (datetime('now','localtime')),
    device_id TEXT, plot TEXT,
    soil_moisture REAL, temperature REAL, humidity REAL, ph REAL,
    nitrogen REAL, phosphorus REAL, potassium REAL,
    soil_temp REAL, light REAL, rainfall REAL);
CREATE INDEX IF NOT EXISTS idx_readings_ts ON readings(ts);

CREATE TABLE IF NOT EXISTS alerts(
    id INTEGER PRIMARY KEY, reading_id INT, device_id TEXT, kind TEXT,
    message TEXT, severity TEXT, ts TEXT DEFAULT (datetime('now','localtime')));
CREATE INDEX IF NOT EXISTS idx_alerts_ts ON alerts(ts);

CREATE TABLE IF NOT EXISTS recommendations(
    id INTEGER PRIMARY KEY, reading_id INT, action TEXT,
    ts TEXT DEFAULT (datetime('now','localtime')));

CREATE TABLE IF NOT EXISTS actuators(
    id INTEGER PRIMARY KEY, device_id TEXT, name TEXT, state TEXT,
    reason TEXT, updated_at TEXT DEFAULT (datetime('now','localtime')),
    UNIQUE(device_id, name));

CREATE TABLE IF NOT EXISTS irrigation_events(
    id INTEGER PRIMARY KEY, device_id TEXT, action TEXT, minutes INT,
    reason TEXT, soil_moisture REAL, rain_forecast REAL,
    ts TEXT DEFAULT (datetime('now','localtime')));

CREATE TABLE IF NOT EXISTS weather(
    id INTEGER PRIMARY KEY, lat REAL, lon REAL, payload TEXT,
    fetched_at TEXT DEFAULT (datetime('now','localtime')));

-- REAL weather observations (Open-Meteo). Kept separate from `readings`,
-- which holds genuine device telemetry only. A modelled value must never be
-- presented as a sensor measurement.
CREATE TABLE IF NOT EXISTS weather_daily(
    id INTEGER PRIMARY KEY, lat REAL, lon REAL, date TEXT,
    temp_max REAL, temp_min REAL, rain_mm REAL, humidity REAL,
    radiation REAL, wind_max REAL,
    fetched_at TEXT DEFAULT (datetime('now','localtime')),
    UNIQUE(lat, lon, date));
CREATE INDEX IF NOT EXISTS idx_weather_date ON weather_daily(date);
"""


def _sql(table_cols: str) -> str:
    table, _, cols = table_cols.partition("(")
    cols = cols.rstrip(")")
    n = len([c for c in cols.split(",") if c.strip()])
    marks = "(" + ",".join(["?"] * n) + ")"
    return f"INSERT INTO {table}({cols}) VALUES{marks}"


def get_conn(db_path=None):
    conn = sqlite3.connect(db_path or DB_PATH, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode = WAL")
    conn.executescript(SCHEMA)
    _migrate(conn)
    return conn
# Columns added after the first release. `CREATE TABLE IF NOT EXISTS` will not
# alter an existing table, so upgrades would silently miss these unless we add
# them explicitly. This keeps an old farm.db working across versions.
_MIGRATIONS = {
    "readings": {
        "device_id": "TEXT", "plot": "TEXT", "soil_temp": "REAL",
        "light": "REAL", "rainfall": "REAL",
    },
    "alerts": {"device_id": "TEXT", "severity": "TEXT"},
}


def _migrate(conn):
    for table, cols in _MIGRATIONS.items():
        existing = {r[1] for r in conn.execute(f"PRAGMA table_info({table})")}
        if not existing:
            continue  # table absent; SCHEMA already created it fresh
        for name, decl in cols.items():
            if name not in existing:
                conn.execute(f"ALTER TABLE {table} ADD COLUMN {name} {decl}")
    conn.commit()


def _now():
    return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")


# ---------------------------------------------------------------- devices ----
def register_device(conn, device_id, plot=None, crop=None, lat=None, lon=None):
    conn.execute(
        "INSERT INTO devices(device_id,plot,crop,lat,lon,last_seen)"
        " VALUES(?,?,?,?,?,?)"
        " ON CONFLICT(device_id) DO UPDATE SET plot=excluded.plot,"
        " crop=excluded.crop, lat=COALESCE(excluded.lat, devices.lat),"
        " lon=COALESCE(excluded.lon, devices.lon), last_seen=excluded.last_seen",
        (device_id, plot, crop, lat, lon, _now()))
    conn.commit()


def devices(conn):
    return [dict(r) for r in conn.execute(
        "SELECT * FROM devices ORDER BY device_id").fetchall()]


# --------------------------------------------------------------- readings ----
def add_reading(conn, reading: dict) -> int:
    row = ask(reading)
    cur = conn.execute(
        _sql("readings(ts,device_id,plot,soil_moisture,temperature,humidity,"
             "ph,nitrogen,phosphorus,potassium,soil_temp,light,rainfall)"), row)
    conn.commit()
    return cur.lastrowid


def ask(reading: dict) -> tuple:
    """Normalise a raw sensor dict into the column order used by INSERT."""
    return (
        reading.get("ts") or _now(),
        reading.get("device_id") or "unknown",
        reading.get("plot"),
        _f(reading.get("soil_moisture")),
        _f(reading.get("temperature")),
        _f(reading.get("humidity")),
        _f(reading.get("ph")),
        _f(reading.get("nitrogen")),
        _f(reading.get("phosphorus")),
        _f(reading.get("potassium")),
        _f(reading.get("soil_temp")),
        _f(reading.get("light")),
        _f(reading.get("rainfall")),
    )


def _f(v):
    try:
        return float(v) if v is not None else None
    except (TypeError, ValueError):
        return None


def latest_reading(conn, device_id=None):
    if device_id:
        row = conn.execute("SELECT * FROM readings WHERE device_id=?"
                           " ORDER BY id DESC LIMIT 1", (device_id,)).fetchone()
    else:
        row = conn.execute("SELECT * FROM readings ORDER BY id DESC LIMIT 1").fetchone()
    return dict(row) if row else None


def readings(conn, limit=50, device_id=None):
    if device_id:
        rows = conn.execute("SELECT * FROM readings WHERE device_id=?"
                            " ORDER BY id DESC LIMIT ?", (device_id, limit)).fetchall()
    else:
        rows = conn.execute("SELECT * FROM readings ORDER BY id DESC LIMIT ?",
                            (limit,)).fetchall()
    return [dict(r) for r in rows]


# ----------------------------------------------------------------- alerts ----
def add_alert(conn, kind, message, severity="info", reading_id=None, device_id=None):
    conn.execute(_sql("alerts(reading_id,device_id,kind,message,severity)"),
                 (reading_id, device_id, kind, message, severity))
    conn.commit()


def add_recommendation(conn, reading_id, action):
    conn.execute(_sql("recommendations(reading_id,action)"), (reading_id, action))
    conn.commit()


def recent_alerts(conn, limit=20):
    return [dict(r) for r in conn.execute(
        "SELECT kind,message,severity,device_id,ts FROM alerts"
        " ORDER BY id DESC LIMIT ?", (limit,)).fetchall()]


# -------------------------------------------------------------- actuators ----
def set_actuator(conn, device_id, name, state, reason=""):
    conn.execute(
        "INSERT INTO actuators(device_id,name,state,reason,updated_at)"
        " VALUES(?,?,?,?,?)"
        " ON CONFLICT(device_id,name) DO UPDATE SET state=excluded.state,"
        " reason=excluded.reason, updated_at=excluded.updated_at",
        (device_id, name, state, reason, _now()))
    conn.commit()


def actuator_states(conn, device_id=None):
    if device_id:
        rows = conn.execute("SELECT * FROM actuators WHERE device_id=?",
                            (device_id,)).fetchall()
    else:
        rows = conn.execute("SELECT * FROM actuators").fetchall()
    return [dict(r) for r in rows]


def log_irrigation(conn, device_id, action, minutes, reason,
                   soil_moisture=None, rain_forecast=None):
    conn.execute(
        _sql("irrigation_events(device_id,action,minutes,reason,soil_moisture,"
             "rain_forecast)"),
        (device_id, action, minutes, reason, soil_moisture, rain_forecast))
    conn.commit()


def last_irrigation(conn, device_id):
    row = conn.execute(
        "SELECT * FROM irrigation_events WHERE device_id=?"
        " ORDER BY id DESC LIMIT 1", (device_id,)).fetchone()
    return dict(row) if row else None


# ---------------------------------------------------------------- weather ----
def cache_weather(conn, lat, lon, payload_json):
    conn.execute(_sql("weather(lat,lon,payload)"), (lat, lon, payload_json))
    conn.commit()


def upsert_weather(conn, lat, lon, date, temp_max=None, temp_min=None,
                   rain_mm=None, humidity=None, radiation=None, wind_max=None):
    """Store one day of REAL weather (idempotent per location+date)."""
    cols = ("lat,lon,date,temp_max,temp_min,rain_mm,humidity,radiation,"
            "wind_max")
    marks = "(" + ",".join(["?"] * len(cols.split(","))) + ")"
    conn.execute(
        "INSERT INTO weather_daily(" + cols + ") VALUES" + marks +
        " ON CONFLICT(lat,lon,date) DO UPDATE SET"
        " temp_max=excluded.temp_max, temp_min=excluded.temp_min,"
        " rain_mm=excluded.rain_mm, humidity=excluded.humidity,"
        " radiation=excluded.radiation, wind_max=excluded.wind_max",
        (lat, lon, date, temp_max, temp_min, rain_mm, humidity, radiation,
         wind_max))


def weather_daily(conn, limit=60, lat=None, lon=None):
    if lat is not None and lon is not None:
        rows = conn.execute(
            "SELECT * FROM weather_daily WHERE lat=? AND lon=?"
            " ORDER BY date DESC LIMIT ?", (lat, lon, limit)).fetchall()
    else:
        rows = conn.execute(
            "SELECT * FROM weather_daily ORDER BY date DESC LIMIT ?",
            (limit,)).fetchall()
    return [dict(r) for r in rows]


def readings_timeseries(conn, hours=48, device_id=None):
    """Genuine device telemetry, most recent first, for the dashboard charts."""
    if device_id:
        rows = conn.execute(
            "SELECT ts, soil_moisture, temperature, humidity, rainfall"
            " FROM readings WHERE device_id=? ORDER BY id DESC LIMIT ?",
            (device_id, hours)).fetchall()
    else:
        rows = conn.execute(
            "SELECT ts, soil_moisture, temperature, humidity, rainfall"
            " FROM readings ORDER BY id DESC LIMIT ?", (hours,)).fetchall()
    return [dict(r) for r in rows][::-1]


def last_weather(conn, lat, lon):
    row = conn.execute(
        "SELECT payload, fetched_at FROM weather WHERE lat=? AND lon=?"
        " ORDER BY id DESC LIMIT 1", (lat, lon)).fetchone()
    return dict(row) if row else None


# ---------------------------------------------------------------- reporting --
def summary(conn):
    return {
        "devices": conn.execute("SELECT COUNT(*) c FROM devices").fetchone()["c"],
        "readings": conn.execute("SELECT COUNT(*) c FROM readings").fetchone()["c"],
        "alerts": conn.execute("SELECT COUNT(*) c FROM alerts").fetchone()["c"],
        "irrigations": conn.execute(
            "SELECT COUNT(*) c FROM irrigation_events").fetchone()["c"],
    }


def export_csv(conn, out_dir=EXPORT_DIR, limit=1000):
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"readings_{datetime.date.today().isoformat()}.csv")
    rows = conn.execute("SELECT * FROM readings ORDER BY id DESC LIMIT ?",
                        (limit,)).fetchall()
    with open(path, "w", newline="", encoding="utf-8") as fh:
        if rows:
            w = csv.DictWriter(fh, fieldnames=rows[0].keys())
            w.writeheader()
            w.writerows([dict(r) for r in rows])
    return path
